### ISSUE TITLE
Plugin Cassandra tasks appearing weirdly on UI

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-cassandra#35]
### Expected Behavior

The tasks should be "Query" and "Trigger".

### Actual Behaviour

<img width="288" alt="Screenshot 2024-01-15 at 8 14 52 PM" src="https://github.com/kestra-io/plugin-cassandra/assets/6594483/9d454015-4bc9-4419-84c5-6415dd4822b6">

### Steps To Reproduce

Go to https://kestra.io/plugins and open the Apache Cassandra's dropdown on the left navigation bar.

### Environment Information

- Kestra Version: N/A
- Plugin version: N/A
- Operating System (OS / Docker / Kubernetes): N/A
- Java Version (If not docker): N/A

**Comment by brian-mulier-p** [comment]
Due to the fact that the group of the plugin is `io.kestra.plugin.cassandra` and there are some tasks starting with `io.kestra.plugin.astradb`.
The solution is to alias every tasks and replace:
- tasks starting with `io.kestra.plugin.cassandra` should start with `io.kestra.plugin.cassandra.native`
- tasks starting with `io.kestra.plugin.astradb` should start with `io.kestra.plugin.cassandra.astradb`
